'''
    Configuration file for trivent processor. Is read by trivent.py
    Usage :    python steer/trivent.py config_trivent 732875,732882
'''

#MRPC Runs
# runList = [732889,732882,732876,732877,732878,732875,732874,732873,732872,732869,732867,732865,732864,732863,732861,732860,732853,732852] # use this list if no runNumber specified when running streamout.py

#MRPC Muons Runs
# runList = ['''732865''', 732864, 732863, 732861, 732860, 732853, '''732852'''] # use this list if no runNumber specified when running streamout.py

# runPeriod = "SPS_12_2014"
# runPeriod = "SPS_04_2015"
# runPeriod = "PS_06_2015"
runPeriod = "SPS_10_2015"
# runPeriod = "SPS_06_2016"

# dataPath = "/Users/antoine/CALICE/DataAnalysis/data"
dataPath = "/Volumes/PagosDisk/CALICE/data/%s" % runPeriod
inputPath = "%s/Streamout" % dataPath
outputPath = "%s/Trivent" % dataPath
plotPath = "%s/Plots" % dataPath
logPath = "%s/Logs" % dataPath
geomPath = "%s/Geometry" % dataPath

logFile = "%s/triventLog_%s" # % (logPath, runNumber)

# geomFile = "%s/m3_bonneteau.xml"  % (geomPath) # use an already
geomFile = "%s/geom_%s_autoGenerated.xml"  % (geomPath, runPeriod)
# geomFile = "%s/m3_bonneteau_avril2015.xml"  % (geomPath)

inputFile = "%s/DHCAL_%d_SO.slcio" # % (intputPath,runNumber) Is parsed by trivent.py to build the xmlFile
outputFile = "%s/TDHCAL_%dTEST" # extension slcio/root added in xml # % (outputPath,runNumber)


processorPath = "/Users/antoine/CALICE/DataAnalysis/triventArnaud"
xmlFile = "%s/TriventProcessor.xml" % processorPath # XML file to be generated
marlinLib = "%s/lib/libTriventArnaud.dylib" % processorPath # Marlin library for processor

processorList = [["MyTriventProc", "TriventProc"]] # List of [name,type]
# verbosity = "DEBUG0"
verbosity = "MESSAGE"

inputCollectionName = "DHCALRawHits"
outputCollectionName = "SDHCAL_HIT"

maxEvt = 10000 # Max Number of event to process
nSkipEvt = 1 # Number of event to skip

gainCorrection = False
electronicNoiseCut = 200000
layerGap = 2.8
layerCut = 7
noiseCut = 10
timeWin = 2
hasCerenkovDif = True
cerenkovDifId = 3
cerenkovTimeWin = 50
# TODO: check for asic/chan/threshold value for each period

if runPeriod.find("2012") != -1:
    hasCerenkovDif = False

elif runPeriod.find("2014") != -1:
    cerenkovDifId = 1
